FROM node:10

ARG NODE_ENV=production
ENV NODE_ENV $NODE_ENV

# you'll likely want the latest npm, regardless of node version, for speed and fixes
# but pin this version for the best stability
RUN npm i npm@latest -g

# install dependencies first, in a different location for easier app bind mounting for local development
WORKDIR /usr/app
COPY package.json package-lock.json* ./
RUN npm install --no-optional && npm cache clean --force

COPY . /usr/app

CMD npm start
