"""initial

Revision ID: 9aa8a77db68b
Revises: 
Create Date: 2018-09-28 16:14:30.638009

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9aa8a77db68b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animes',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('anilist_id', sa.Integer(), nullable=True),
    sa.Column('mal_id', sa.Integer(), nullable=True),
    sa.Column('raw_name', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('archives',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('link_url', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characters',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('anilist_id', sa.Integer(), nullable=True),
    sa.Column('raw_name', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('certainty', sa.Integer(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anime_appearances',
    sa.Column('character_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('anime_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['anime_id'], ['animes.id'], ),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], )
    )
    op.create_table('files',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('anime_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('archive_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('link_url', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['animes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['archive_id'], ['archives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seasons',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('anime_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('raw_name', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['anime_id'], ['animes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('episodes',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('anime_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('season_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('file_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('episode_number', sa.String(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('sub_group', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['anime_id'], ['animes.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('season_appearances',
    sa.Column('character_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('season_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], )
    )
    op.create_table('dialogues',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('character_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('episode_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('season_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('anime_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('start', sa.Integer(), nullable=False),
    sa.Column('end', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['anime_id'], ['animes.id'], ),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('episode_appearances',
    sa.Column('character_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('episode_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('episode_appearances')
    op.drop_table('dialogues')
    op.drop_table('season_appearances')
    op.drop_table('episodes')
    op.drop_table('seasons')
    op.drop_table('files')
    op.drop_table('anime_appearances')
    op.drop_table('characters')
    op.drop_table('archives')
    op.drop_table('animes')
    # ### end Alembic commands ###
